Vagrant.configure("2") do |config|
  config.vm.define "preprod-box" do |preprod|
    preprod.vm.box = "ubuntu/xenial64"
    preprod.vm.hostname = "preprod-box"

  config.vm.provision "shell", inline: <<-SHELL
    # Mettre à jour les paquets
    sudo apt-get update

    # Installer Java JDK
    sudo apt-get install -y openjdk-17-jdk

    # Installer Docker
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce

    # Installer Docker Compose
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    
    # Créer un dossier 'app' et donner les autorisations nécessaires
    sudo mkdir /app
    sudo chmod -R 777 /app

  SHELL
end

