Vagrant.configure("2") do |config|
  config.vm.define "dev-qa-box" do |dev|
    dev.vm.box = "ubuntu/xenial64"
    dev.vm.network "private_network", ip: "192.168.56.101"
    dev.vm.hostname = "dev-qa-box"
    
    # Configuration SSH pour rester connecté
    dev.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.provision "shell", inline: <<-SHELL
      # Mettre à jour les paquets
      sudo apt-get update

      # Installer Java JDK
      sudo apt-get install -y openjdk-17-jdk 

      # Installer Docker
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common unzip
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce

      # Installer Docker Compose
      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose

      # Créer un dossier 'app' et donner les autorisations nécessaires
      sudo mkdir /app
      sudo chmod -R 777 /app
    SHELL
  end
end
